events { worker_connections 1024; }
http {
    server {
        listen 81;
        server_name localhost;
        
        client_max_body_size 0;
        
        root /usr/share/nginx/html;

        location / {
            try_files $uri $uri/ /index.html =404;
        }
    }
}