version: "3.5"

services:
  backend_server:
    image: backend
    build: ./backend
    ports:
      - "8000:5071"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend_server:
    image: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8181:81"
    container_name: errorline-system-frontend
    depends_on:
      - backend_server

#  postgres_server:
#   image: postgres:13.2-alpine
#   restart: unless-stopped
#   environment:
#     POSTGRES_PASSWORD: postgres
#   container_name: postgres
#   volumes:
#     - database:/var/lib/postgresql/data

  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

volumes:
  database: